cloud:
  aws:
    region:
      static: us-east-1
  credentials:
    profile-name: default
spring:
  data:
    redis:
      host: clustercfg.pms-redis-userservice-session.tydzty.aps1.cache.amazonaws.com
      port: 6379
      password: 02081991user-session-service
